name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      convex-peer:
        image: convexdev/convex:latest
        ports:
          - 18888:18888
          - 18889:18889
        env:
          CONVEX_PEER_PORT: 18888
          CONVEX_ADMIN_PORT: 18889
          CONVEX_NETWORK: test
        options: >-
          --health-cmd "curl -f http://localhost:18888/api/v1/status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
          --health-start-period 30s

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Wait for Convex peer
        run: |
          timeout 60s bash -c 'until curl -s http://localhost:18888/api/v1/status; do sleep 1; done'

      - name: Run tests
        run: pnpm test
        env:
          CONVEX_PEER_URL: http://localhost:18888 